import pandas as pd

# Students' marks
marks = [45,50,55,60,65,70,75,80,95,150]

df = pd.DataFrame({'Marks': marks})

Q1 = df['Marks'].quantile(0.25)
Q3 = df['Marks'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[(df['Marks'] < lower) | (df['Marks'] > upper)]

print("Q1 =", Q1)
print("Q3 =", Q3)
print("IQR =", IQR)

print("\nOutliers:")
print(outliers)
