import pandas as pd
import matplotlib.pyplot as plt

# Dataset
data = [10,12,14,15,16,18,20,22,24,100]

df = pd.DataFrame({'Value': data})

# IQR
Q1 = df['Value'].quantile(0.25)
Q3 = df['Value'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

# Remove outliers
clean = df[(df['Value'] >= lower) & (df['Value'] <= upper)]

print("Original Data:")
print(df)

print("\nCleaned Data:")
print(clean)

# Histogram Before
plt.figure()
plt.hist(df['Value'])
plt.title("Histogram Before Removing Outliers")
plt.show()

# Box Plot Before
plt.figure()
plt.boxplot(df['Value'])
plt.title("Box Plot Before")
plt.show()

# Check if cleaned data is available
if len(clean) > 0:

    # Histogram After
    plt.figure()
    plt.hist(clean['Value'])
    plt.title("Histogram After Removing Outliers")
    plt.show()

    # Box Plot After
    plt.figure()
    plt.boxplot(clean['Value'])
    plt.title("Box Plot After")
    plt.show()

else:
    print("No data left after removing outliers.")
