import matplotlib.pyplot as plt

# Monthly sales data
months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun"]
sales = [12000, 15000, 18000, 17000, 20000, 22000]

# Line Plot
plt.figure(figsize=(10,4))

plt.subplot(1,2,1)
plt.plot(months, sales, marker='o')
plt.title("Monthly Sales Line Plot")
plt.xlabel("Month")
plt.ylabel("Sales")

# Bar Plot
plt.subplot(1,2,2)
plt.bar(months, sales)
plt.title("Monthly Sales Bar Plot")
plt.xlabel("Month")
plt.ylabel("Sales")

plt.tight_layout()
plt.show()
